% -------------------------------------------------------------------------
% Name: calcu_muscle_excitation
% Author(s): Jin Wei, Peking U. wjin24@stu.pku.edu.cn
% Description: calculate the control signals of the muslces (i.e., muscle
% excitations) using muscle reflex mechanism, where the muscle excitations
% are generated by the virtual CNS (Central Neural System) while
% incorporating intrinsic signals like muslce states and joint angles, and
% extrinsic feedback like ground reaction forces and other external forces/
% torques.
%     The four basic muscle reflex feedbacks for each muscle:
%     - [constant stimulation]: sigma_const = C
%     - [force feedback]: sigma_F± = ±K_F * F'
%     - [length feedback]: sigma_L± = ±K_L * (l' - l_0')
%     - [joint angle feedback]: sigma_q± = ±(K_q * (q-q0) + K_dq * dq)
%     More details are available in:
%     Jin W, Liu J, Zhan Q, etc. Forward dynamics simulation of a
%     simplified neuromuscular-skeleta-exoskeletal model based on the
%     CMA-ES optimization algorithm: Framework and case studies[J]. Multibody
%     system dynamics, 2024.
% Input:
%
% Output:
%
% -------------------------------------------------------------------------

function muscleExcitations = cal_muscle_excitation(modelInfo, frameIndex)
% Muscle order (7 per leg, R then L):
%   1=hamR, 2=gluR, 3=iliR, 4=vasR, 5=gasR, 6=solR, 7=tibR
%   8=hamL, 9=gluL, 10=iliL, 11=vasL, 12=gasL, 13=solL, 14=tibL

map = modelInfo.st.model.map;
p   = modelInfo.dy.muscle.para;  % reflex parameter struct

% ---- extract current-frame muscle state vectors ----
fATN_frame = modelInfo.dy.muscle.fATN(:, frameIndex);
lCEN_frame = modelInfo.dy.muscle.lCEN(:, frameIndex);

% ---- joint states (pelvis tilt, knee angles / velocities) ----
if frameIndex == 1
    initPose  = modelInfo.st.model.initPose;
    pelvisTilt  = initPose(map('pelvis_tilt/value'));
    pelvisTiltV = initPose(map('pelvis_tilt/speed'));
    kneeAngR = initPose(map('knee_flexion_r/value'));
    kneeVelR = initPose(map('knee_flexion_r/speed'));
    kneeAngL = initPose(map('knee_flexion_l/value'));
    kneeVelL = initPose(map('knee_flexion_l/speed'));
else
    sh = modelInfo.dy.stateHistory;
    pelvisTilt  = sh(map('pelvis_tilt/value'), frameIndex - 1);
    pelvisTiltV = sh(map('pelvis_tilt/speed'), frameIndex - 1);
    kneeAngR = sh(map('knee_flexion_r/value'), frameIndex - 1);
    kneeVelR = sh(map('knee_flexion_r/speed'), frameIndex - 1);
    kneeAngL = sh(map('knee_flexion_l/value'), frameIndex - 1);
    kneeVelL = sh(map('knee_flexion_l/speed'), frameIndex - 1);
end

% ---- compute excitation per leg (same reflex rules, independent leg state) ----
nMusPerLeg = numel(modelInfo.st.muscle.names) / 2;  % 7 muscles per leg
baseIdxR = 0;            % right-leg muscles occupy indices 1..7  (R-L ordering)
baseIdxL = nMusPerLeg;   % left-leg  muscles occupy indices 8..14
muscleIdx = modelInfo.st.muscle.legIdx;  % built once in read_muscle_static_prop

excR = compute_leg_excitation(modelInfo.dy.phase.r(frameIndex), fATN_frame, lCEN_frame, ...
    p, pelvisTilt, pelvisTiltV, kneeAngR, kneeVelR, baseIdxR, muscleIdx);
excL = compute_leg_excitation(modelInfo.dy.phase.l(frameIndex), fATN_frame, lCEN_frame, ...
    p, pelvisTilt, pelvisTiltV, kneeAngL, kneeVelL, baseIdxL, muscleIdx);

% ---- assemble 14-element output ----
muscleExcitations = [excR; excL];

% ---- clip to physiological range [0, 1] ----
muscleExcitations(muscleExcitations > 1) = 1;
muscleExcitations(muscleExcitations < 0) = 0;

end

% ========================================================================
function exc = compute_leg_excitation(phase, fATN, lCEN, p, ...
    pelvisTilt, pelvisTiltV, kneeAng, kneeVel, baseIdx, muscleIdx)
% Compute the 7 muscle excitations for a single leg using the muscle-reflex
% controller.  baseIdx is the 0-based offset of this leg's muscles within
% the full 14-muscle arrays.  muscleIdx maps base muscle name → within-leg
% position (1-based), built dynamically from the right-leg keys in caller.
%
% Phase legend: 0=Early Stance, 1=Late Stance, 2=Liftoff, 3=Swing, 4=Landing

% ---- per-leg muscle positions (1-based, from dynamic map) ----
HAM = muscleIdx('hamstrings');
GLU = muscleIdx('glut_max');
ILI = muscleIdx('iliopsoas');
VAS = muscleIdx('vasti');
GAS = muscleIdx('gastroc');
SOL = muscleIdx('soleus');
TIB = muscleIdx('tibia');

% ---- muscle states for this leg ----
gluFN = fATN(baseIdx + GLU);
vasFN = fATN(baseIdx + VAS);
gasFN = fATN(baseIdx + GAS);
solFN = fATN(baseIdx + SOL);
hamLN = lCEN(baseIdx + HAM);
iliLN = lCEN(baseIdx + ILI);
tibLN = lCEN(baseIdx + TIB);

% ---- shared constants ----
P0_pq = -0.1944;  % reference pelvis tilt angle

% ---- vasti knee-extension gating ----
deltaVas = double(kneeAng < p.vas_knee.pos_max || kneeVel <= 0);

% ---- per-phase excitation ----
exc = zeros(7, 1);

switch phase
    case {0, 1}  % early / late stance
        exc(HAM) = p.ham_pelvis_tilt.C0 - (p.ham_pelvis_tilt.KP * (pelvisTilt - P0_pq) + p.ham_pelvis_tilt.KV * pelvisTiltV);
        exc(GLU) = p.glu_pelvis_tilt.C0 - (p.glu_pelvis_tilt.KP * (pelvisTilt - P0_pq) + p.glu_pelvis_tilt.KV * pelvisTiltV);
        exc(ILI) = p.ili_pelvis_tilt.C0 - (p.ili_pelvis_tilt.KP * (pelvisTilt - P0_pq) + p.ili_pelvis_tilt.KV * pelvisTiltV);

        if phase == 0
            exc(VAS) = p.vas.C0 + deltaVas * p.vas.KF1 * vasFN;
        else
            exc(VAS) = p.vas.C0 + deltaVas * p.vas.KF2 * vasFN;
        end

        exc(GAS) = p.gas.KF * gasFN;
        exc(SOL) = p.sol.KF * solFN;
        exc(TIB) = p.tib.KL * (tibLN - p.tib.L0) + p.tib_sol.KF * solFN;

    case 2  % liftoff
        exc(ILI) = p.ili.C0;
        exc(GAS) = p.gas.KF * gasFN;
        exc(SOL) = p.sol.KF * solFN;
        exc(TIB) = p.tib.KL * (tibLN - p.tib.L0) + p.tib_sol.KF * solFN;

    case 3  % swing
        exc(GLU) = p.glu.KF * gluFN;
        exc(ILI) = p.ili.KL * (iliLN - p.ili.L0) ...
                 - p.ili_pelvis_tilt.KP2 * (pelvisTilt - p.ili_pelvis_tilt.P02) ...
                 + p.ili_ham.KL * (hamLN - p.ili_ham.L0) ...
                 - p.ili_pelvis_tilt.KV2 * pelvisTiltV;
        exc(TIB) = p.tib.KL * (tibLN - p.tib.L0) + p.tib_sol.KF * solFN;

    case 4  % landing
        exc(HAM) = p.ham_glu.KF * gluFN;
        exc(GLU) = p.glu.KF * gluFN;
        exc(ILI) = p.ili.KL * (iliLN - p.ili.L0) ...
                 - p.ili_pelvis_tilt.KP2 * (pelvisTilt - p.ili_pelvis_tilt.P02) ...
                 + p.ili_ham.KL * (hamLN - p.ili_ham.L0) ...
                 - p.ili_pelvis_tilt.KV2 * pelvisTiltV;
        exc(TIB) = p.tib.KL * (tibLN - p.tib.L0) + p.tib_sol.KF * solFN;

    otherwise
        error('Invalid gait phase: %d', phase);
end

end