% -------------------------------------------------------------------------
% Name: calcu_muscle_excitation
% Author(s): Jin Wei, Peking U. wjin24@stu.pku.edu.cn
% Description: calculate the control signals of the muslces (i.e., muscle
% excitations) using muscle reflex mechanism, where the muscle excitations
% are generated by the virtual CNS (Central Neural System) while
% incorporating intrinsic signals like muslce states and joint angles, and
% extrinsic feedback like ground reaction forces and other external forces/
% torques.
%     The four basic muscle reflex feedbacks for each muscle:
%     - [constant stimulation]: sigma_const = C
%     - [force feedback]: sigma_F± = ±K_F * F'
%     - [length feedback]: sigma_L± = ±K_L * (l' - l_0')
%     - [joint angle feedback]: sigma_q± = ±(K_q * (q-q0) + K_dq * dq)
%     More details are available in:
%     Jin W, Liu J, Zhan Q, etc. Forward dynamics simulation of a
%     simplified neuromuscular-skeleta-exoskeletal model based on the
%     CMA-ES optimization algorithm: Framework and case studies[J]. Multibody
%     system dynamics, 2024.
% Input:
%
% Output:
%
% -------------------------------------------------------------------------

function muscleExcitations = cal_muscle_excitation(modelInfo, frameIndex)
% Name: cal_muscle_excitation
% Description: Compute 14×1 muscle excitation vector for the current frame.
%   Supports two controller modes:
%     - LASSO linear-phase controller (if modelInfo.reflexParams is nonempty)
%     - Legacy hand-crafted reflex controller (fallback)
%
%   Muscle order (7 per leg, R then L):
%     1=hamR, 2=gluR, 3=iliR, 4=vasR, 5=gasR, 6=solR, 7=tibR
%     8=hamL, 9=gluL, 10=iliL, 11=vasL, 12=gasL, 13=solL, 14=tibL

%% ---- dispatch: LASSO vs legacy ----
if ~isempty(modelInfo.reflexParams) ...
        && strcmp(modelInfo.reflexParams.controllerType, 'lasso_linear_phase')

    % ======== LASSO linear-phase controller ========
    muscleExcitations = lasso_excitation(modelInfo, frameIndex);

else
    error('Legacy hand-crafted controller is commented.');
    % % ======== legacy hand-crafted controller ========
    % muscleExcitations = legacy_excitation(modelInfo, frameIndex);
end

% ---- clip to physiological range [0, 1] ----
muscleExcitations(muscleExcitations > 1) = 1;
muscleExcitations(muscleExcitations < 0) = 0;

end

% ========================================================================
function exc = lasso_excitation(modelInfo, frameIndex)
% LASSO sparse linear-phase controller.
%   excitation_side = A_side * beta{phaseIdx} + bias{phaseIdx}

rp = modelInfo.reflexParams;
rt = modelInfo.reflexTemplate;

% ---- right leg ----
phaseR = modelInfo.dy.phase.r(frameIndex);
phaseIdxR = find(rt.phaseIds == phaseR, 1);
if isempty(phaseIdxR)
    error('LASSO: unknown right-leg phase ID %d at frame %d.', phaseR, frameIndex);
end
A_R = extract_lasso_reflex_features(modelInfo, 'right', frameIndex);
excR = A_R * rp.beta{phaseIdxR} + rp.bias{phaseIdxR};  % 1×7

% ---- left leg (same canonical beta/bias, different features) ----
phaseL = modelInfo.dy.phase.l(frameIndex);
phaseIdxL = find(rt.phaseIds == phaseL, 1);
if isempty(phaseIdxL)
    error('LASSO: unknown left-leg phase ID %d at frame %d.', phaseL, frameIndex);
end
A_L = extract_lasso_reflex_features(modelInfo, 'left', frameIndex);
excL = A_L * rp.beta{phaseIdxL} + rp.bias{phaseIdxL};  % 1×7

% ---- assemble 14×1 column: [right 1:7; left 8:14] ----
exc = [excR(:); excL(:)];
end

% % ========================================================================
% function exc = legacy_excitation(modelInfo, frameIndex)
% % Original hand-crafted muscle-reflex controller (preserved as fallback).
%
% map = modelInfo.st.model.map;
% p   = modelInfo.dy.muscle.para;
%
% fATN_frame = modelInfo.dy.muscle.fATN(:, frameIndex);
% lCEN_frame = modelInfo.dy.muscle.lCEN(:, frameIndex);
%
% if frameIndex == 1
%     initPose  = modelInfo.st.model.initPose;
%     pelvisTilt  = initPose(map('pelvis_tilt/value'));
%     pelvisTiltV = initPose(map('pelvis_tilt/speed'));
%     kneeAngR = initPose(map('knee_extension_r/value'));
%     kneeVelR = initPose(map('knee_extension_r/speed'));
%     kneeAngL = initPose(map('knee_extension_l/value'));
%     kneeVelL = initPose(map('knee_extension_l/speed'));
% else
%     sh = modelInfo.dy.stateHistory;
%     pelvisTilt  = sh(map('pelvis_tilt/value'), frameIndex - 1);
%     pelvisTiltV = sh(map('pelvis_tilt/speed'), frameIndex - 1);
%     kneeAngR = sh(map('knee_extension_r/value'), frameIndex - 1);
%     kneeVelR = sh(map('knee_extension_r/speed'), frameIndex - 1);
%     kneeAngL = sh(map('knee_extension_l/value'), frameIndex - 1);
%     kneeVelL = sh(map('knee_extension_l/speed'), frameIndex - 1);
% end
%
% nMusPerLeg = numel(modelInfo.st.muscle.names) / 2;
% baseIdxR = 0;
% baseIdxL = nMusPerLeg;
% muscleIdx = modelInfo.st.muscle.legIdx;
%
% excR = compute_leg_excitation(modelInfo.dy.phase.r(frameIndex), fATN_frame, lCEN_frame, ...
%     p, pelvisTilt, pelvisTiltV, kneeAngR, kneeVelR, baseIdxR, muscleIdx);
% excL = compute_leg_excitation(modelInfo.dy.phase.l(frameIndex), fATN_frame, lCEN_frame, ...
%     p, pelvisTilt, pelvisTiltV, kneeAngL, kneeVelL, baseIdxL, muscleIdx);
%
% exc = [excR; excL];
% end
%
% % ========================================================================
% function exc = compute_leg_excitation(phase, fATN, lCEN, p, ...
%     pelvisTilt, pelvisTiltV, kneeAng, kneeVel, baseIdx, muscleIdx)
% % Legacy per-leg excitation (preserved from original code).
%
% HAM = muscleIdx('hamstrings');
% GLU = muscleIdx('glut_max');
% ILI = muscleIdx('iliopsoas');
% VAS = muscleIdx('vasti');
% GAS = muscleIdx('gastroc');
% SOL = muscleIdx('soleus');
% TIB = muscleIdx('tib_ant');
%
% gluFN = fATN(baseIdx + GLU);
% vasFN = fATN(baseIdx + VAS);
% gasFN = fATN(baseIdx + GAS);
% solFN = fATN(baseIdx + SOL);
% hamLN = lCEN(baseIdx + HAM);
% iliLN = lCEN(baseIdx + ILI);
% tibLN = lCEN(baseIdx + TIB);
%
% P0_pq = -0.1944;
% deltaVas = double(kneeAng < p.vas_knee.pos_max || kneeVel <= 0);
% exc = zeros(7, 1);
%
% switch phase
%     case {0, 1}
%         exc(HAM) = p.ham_pelvis_tilt.C0 - (p.ham_pelvis_tilt.KP * (pelvisTilt - P0_pq) + p.ham_pelvis_tilt.KV * pelvisTiltV);
%         exc(GLU) = p.glu_pelvis_tilt.C0 - (p.glu_pelvis_tilt.KP * (pelvisTilt - P0_pq) + p.glu_pelvis_tilt.KV * pelvisTiltV);
%         exc(ILI) = p.ili_pelvis_tilt.C0 - (p.ili_pelvis_tilt.KP * (pelvisTilt - P0_pq) + p.ili_pelvis_tilt.KV * pelvisTiltV);
%         if phase == 0
%             exc(VAS) = p.vas.C0 + deltaVas * p.vas.KF1 * vasFN;
%         else
%             exc(VAS) = p.vas.C0 + deltaVas * p.vas.KF2 * vasFN;
%         end
%         exc(GAS) = p.gas.KF * gasFN;
%         exc(SOL) = p.sol.KF * solFN;
%         exc(TIB) = p.tib.KL * (tibLN - p.tib.L0) + p.tib_sol.KF * solFN;
%
%     case 2
%         exc(ILI) = p.ili.C0;
%         exc(GAS) = p.gas.KF * gasFN;
%         exc(SOL) = p.sol.KF * solFN;
%         exc(TIB) = p.tib.KL * (tibLN - p.tib.L0) + p.tib_sol.KF * solFN;
%
%     case 3
%         exc(GLU) = p.glu.KF * gluFN;
%         exc(ILI) = p.ili.KL * (iliLN - p.ili.L0) ...
%                  - p.ili_pelvis_tilt.KP2 * (pelvisTilt - p.ili_pelvis_tilt.P02) ...
%                  + p.ili_ham.KL * (hamLN - p.ili_ham.L0) ...
%                  - p.ili_pelvis_tilt.KV2 * pelvisTiltV;
%         exc(TIB) = p.tib.KL * (tibLN - p.tib.L0) + p.tib_sol.KF * solFN;
%
%     case 4
%         exc(HAM) = p.ham_glu.KF * gluFN;
%         exc(GLU) = p.glu.KF * gluFN;
%         exc(ILI) = p.ili.KL * (iliLN - p.ili.L0) ...
%                  - p.ili_pelvis_tilt.KP2 * (pelvisTilt - p.ili_pelvis_tilt.P02) ...
%                  + p.ili_ham.KL * (hamLN - p.ili_ham.L0) ...
%                  - p.ili_pelvis_tilt.KV2 * pelvisTiltV;
%         exc(TIB) = p.tib.KL * (tibLN - p.tib.L0) + p.tib_sol.KF * solFN;
%
%     otherwise
%         error('Invalid gait phase: %d', phase);
% end
% end