% -------------------------------------------------------------------------
% Name: calcu_muscle_excitation
% Author(s): Jin Wei, Peking U. wjin24@stu.pku.edu.cn
% Description: calculate the control signals of the muslces (i.e., muscle
% excitations) using muscle reflex mechanism, where the muscle excitations
% are generated by the virtual CNS (Central Neural System) while
% incorporating intrinsic signals like muslce states and joint angles, and
% extrinsic feedback like ground reaction forces and other external forces/
% torques.
%     The four basic muscle reflex feedbacks for each muscle:
%     - [constant stimulation]: sigma_const = C
%     - [force feedback]: sigma_F± = ±K_F * F'
%     - [length feedback]: sigma_L± = ±K_L * (l' - l_0')
%     - [joint angle feedback]: sigma_q± = ±(K_q * (q-q0) + K_dq * dq)
%     More details are available in:
%     Jin W, Liu J, Zhan Q, etc. Forward dynamics simulation of a
%     simplified neuromuscular-skeleta-exoskeletal model based on the
%     CMA-ES optimization algorithm: Framework and case studies[J]. Multibody
%     system dynamics, 2024.
% Input:
%
% Output:
%
% -------------------------------------------------------------------------

function muscleExcitations = cal_muscle_excitation(modelInfo, state, frameIndex)
%% Load gait phases
phaseR  = modelInfo.phaseR(frameIndex);
phaseL  = modelInfo.phaseL(frameIndex);

%% Load normalized fiber length and force along tendon
% hamR_FN = modelInfo.muscleFiberForcesATN(1, frameIndex);
gluR_FN = modelInfo.muscleFiberForcesATN(2, frameIndex);
vasR_FN = modelInfo.muscleFiberForcesATN(4, frameIndex);
gasR_FN = modelInfo.muscleFiberForcesATN(5, frameIndex);
solR_FN = modelInfo.muscleFiberForcesATN(6, frameIndex);
% hamL_FN = modelInfo.muscleFiberForcesATN(8, frameIndex);
gluL_FN = modelInfo.muscleFiberForcesATN(9, frameIndex);
vasL_FN = modelInfo.muscleFiberForcesATN(11, frameIndex);
gasL_FN = modelInfo.muscleFiberForcesATN(12, frameIndex);
solL_FN = modelInfo.muscleFiberForcesATN(13, frameIndex);

hamR_LN = modelInfo.muscleFiberLengthN(1, frameIndex);
iliR_LN = modelInfo.muscleFiberLengthN(3, frameIndex);
tibR_LN = modelInfo.muscleFiberLengthN(7, frameIndex);
hamL_LN = modelInfo.muscleFiberLengthN(8, frameIndex);
iliL_LN = modelInfo.muscleFiberLengthN(10, frameIndex);
tibL_LN = modelInfo.muscleFiberLengthN(14, frameIndex);

%% Load muscle reflex parameters
KL_tib              = modelInfo.muscleReflex.tib.KL;
L0_tib              = modelInfo.muscleReflex.tib.L0;
KF_tib_sol          = modelInfo.muscleReflex.tib_sol.KF;
KF_sol              = modelInfo.muscleReflex.sol.KF;
KF_gas              = modelInfo.muscleReflex.gas.KF;
KF1_vas             = modelInfo.muscleReflex.vas.KF1;
KF2_vas             = modelInfo.muscleReflex.vas.KF2;
C0_vas              = modelInfo.muscleReflex.vas.C0;
Max_vas_knee        = modelInfo.muscleReflex.vas_knee.pos_max;
KP_ham_pq           = modelInfo.muscleReflex.ham_pelvis_tilt.KP;
KV_ham_pq           = modelInfo.muscleReflex.ham_pelvis_tilt.KV;
C0_ham_pq           = modelInfo.muscleReflex.ham_pelvis_tilt.C0;
KP_glu_pq           = modelInfo.muscleReflex.glu_pelvis_tilt.KP;
KV_glu_pq           = modelInfo.muscleReflex.glu_pelvis_tilt.KV;
C0_glu_pq           = modelInfo.muscleReflex.glu_pelvis_tilt.C0;
KP_ili_pq           = modelInfo.muscleReflex.ili_pelvis_tilt.KP;
KV_ili_pq           = modelInfo.muscleReflex.ili_pelvis_tilt.KV;
C0_ili_pq           = modelInfo.muscleReflex.ili_pelvis_tilt.C0;
C0_ili              = modelInfo.muscleReflex.ili.C0;
% C0_glu              = modelInfo.muscleReflex.glu.C0;
KL_ili              = modelInfo.muscleReflex.ili.KL;
L0_ili              = modelInfo.muscleReflex.ili.L0;
P0_pq               = -0.1944;
P0_ili_pq2          = modelInfo.muscleReflex.ili_pelvis_tilt.P02;
KP2_ili_pq          = modelInfo.muscleReflex.ili_pelvis_tilt.KP2;
KV2_ili_pq          = modelInfo.muscleReflex.ili_pelvis_tilt.KV2;
KL_ili_ham          = modelInfo.muscleReflex.ili_ham.KL;
L0_ili_ham          = modelInfo.muscleReflex.ili_ham.L0;
% KF_ham              = modelInfo.muscleReflex.ham.KF;
KF_glu              = modelInfo.muscleReflex.glu.KF;
KF_ham_glu          = modelInfo.muscleReflex.ham_glu.KF;

%% Load coordinate pose & velocity needed in muscle reflex mechanism
pq                  = state.getQ.get(0);
pqV                 = state.getU.get(0);
kneeR               = state.getQ.get(5);
kneeRV              = state.getU.get(5);
kneeL               = state.getQ.get(6);
kneeLV              = state.getU.get(6);

%% Calculate muscle excitations based on muscle reflex mechanism
% 注意现在还是左右腿参数相同的。之后要换成左右腿参数独立
muscleNum = height(modelInfo.muscleExcitations);
muscleExcitations = zeros(muscleNum, 1);
hamR_exc = 0; gluR_exc = 0; iliR_exc = 0; vasR_exc = 0; gasR_exc = 0; solR_exc = 0; tibR_exc = 0;
hamL_exc = 0; gluL_exc = 0; iliL_exc = 0; vasL_exc = 0; gasL_exc = 0; solL_exc = 0; tibL_exc = 0;

switch phaseR
    case 0 % early stance
        % hamstrings
        hamR_exc = C0_ham_pq - ( KP_ham_pq*(pq-P0_pq) + KV_ham_pq*pqV );
        % gluteus maximus
        gluR_exc = C0_glu_pq - ( KP_glu_pq*(pq-P0_pq) + KV_glu_pq*pqV );
        % ilipsoas
        iliR_exc = C0_ili_pq - (KP_ili_pq*(pq-P0_pq) + KV_ili_pq*pqV);
        % vasti (rectus femoris)
        delta = 0;
        if kneeR < Max_vas_knee || kneeRV <= 0
            delta = 1;
        end
        vasR_exc = C0_vas + delta * KF1_vas * vasR_FN;
        % gastrocnemius
        gasR_exc = KF_gas * gasR_FN;
        % soleus
        solR_exc = KF_sol * solR_FN;
        % tibialis anterior
        tibR_exc = KL_tib * (tibR_LN - L0_tib) + KF_tib_sol * solR_FN;

    case 1 % late stance
        % hamstrings
        hamR_exc = C0_ham_pq - ( KP_ham_pq*(pq-P0_pq) + KV_ham_pq*pqV );
        % gluteus maximus
        gluR_exc = C0_glu_pq - ( KP_glu_pq*(pq-P0_pq) + KV_glu_pq*pqV );
        % ilipsoas
        iliR_exc = C0_ili_pq - (KP_ili_pq*(pq-P0_pq) + KV_ili_pq*pqV);
        % vasti (rectus femoris)
        delta = 0;
        if kneeR < Max_vas_knee || kneeRV <= 0
            delta = 1;
        end
        vasR_exc = C0_vas + delta * KF2_vas * vasR_FN;
        % gastrocnemius
        gasR_exc = KF_gas * gasR_FN;
        % soleus
        solR_exc = KF_sol * solR_FN;
        % tibialis anterior
        tibR_exc = KL_tib * (tibR_LN - L0_tib) + KF_tib_sol * solR_FN;

    case 2 % liftoff
        % ilipsoas
        iliR_exc = C0_ili;
        % gastrocnemius
        gasR_exc = KF_gas * gasR_FN;
        % soleus
        solR_exc = KF_sol * solR_FN;
        % tibialis anterior
        tibR_exc = KL_tib * (tibR_LN - L0_tib) + KF_tib_sol * solR_FN;

    case 3 % swing
        % vastus
        % vasR_exc = 
        % gluteus maximus
        gluR_exc = KF_glu * gluR_FN;
        % ilipsoas
        iliR_exc =  KL_ili*(iliR_LN-L0_ili) - (KP2_ili_pq*(pq-P0_ili_pq2)) + KL_ili_ham*(hamR_LN-L0_ili_ham) - KV2_ili_pq*pqV;
        % tibialis anterior
        tibR_exc = KL_tib * (tibR_LN - L0_tib) + KF_tib_sol * solR_FN;

    case 4 % landing
        % hamstrings
        hamR_exc = KF_ham_glu * gluR_FN;
        % gluteus maximus
        gluR_exc = KF_glu * gluR_FN;
        % ilipsoas
        iliR_exc =  KL_ili*(iliR_LN-L0_ili) - (KP2_ili_pq*(pq-P0_ili_pq2)) + KL_ili_ham*(hamR_LN-L0_ili_ham) - KV2_ili_pq*pqV;
        % tibialis anterior
        tibR_exc = KL_tib * (tibR_LN - L0_tib) + KF_tib_sol * solR_FN;

    otherwise
        error('invalid muscle index.');
end

switch phaseL
    case 0 % early stance
        % hamstrings
        hamL_exc = C0_ham_pq - ( KP_ham_pq*(pq-P0_pq) + KV_ham_pq*pqV );
        % gluteus maximus
        gluL_exc = C0_glu_pq - ( KP_glu_pq*(pq-P0_pq) + KV_glu_pq*pqV );
        % ilipsoas
        iliL_exc = C0_ili_pq - (KP_ili_pq*(pq-P0_pq) + KV_ili_pq*pqV);
        % vasti (rectus femoris)
        delta = 0;
        if kneeL < Max_vas_knee || kneeLV <= 0
            delta = 1;
        end
        vasL_exc = C0_vas + delta * KF1_vas * vasL_FN;
        % gastrocnemius
        gasL_exc = KF_gas * gasL_FN;
        % soleus
        solL_exc = KF_sol * solL_FN;
        % tibialis anterior
        tibL_exc = KL_tib * (tibL_LN - L0_tib) + KF_tib_sol * solL_FN;

    case 1 % late stance
        % hamstrings
        hamL_exc = C0_ham_pq - ( KP_ham_pq*(pq-P0_pq) + KV_ham_pq*pqV );
        % gluteus maximus
        gluL_exc = C0_glu_pq - ( KP_glu_pq*(pq-P0_pq) + KV_glu_pq*pqV );
        % ilipsoas
        iliL_exc = C0_ili_pq - (KP_ili_pq*(pq-P0_pq) + KV_ili_pq*pqV);
        % vasti (rectus femoris)
        delta = 0;
        if kneeL < Max_vas_knee || kneeLV <= 0
            delta = 1;
        end
        vasL_exc = C0_vas + delta * KF2_vas * vasL_FN;
        % gastrocnemius
        gasL_exc = KF_gas * gasL_FN;
        % soleus
        solL_exc = KF_sol * solL_FN;
        % tibialis anterior
        tibL_exc = KL_tib * (tibL_LN - L0_tib) + KF_tib_sol * solL_FN;

    case 2 % liftoff
        % ilipsoas
        iliL_exc = C0_ili;
        % gastrocnemius
        gasL_exc = KF_gas * gasL_FN;
        % soleus
        solL_exc = KF_sol * solL_FN;
        % tibialis anterior
        tibL_exc = KL_tib * (tibL_LN - L0_tib) + KF_tib_sol * solL_FN;

    case 3 % swing
        % gluteus maximus
        gluL_exc = KF_glu * gluL_FN;
        % ilipsoas
        iliL_exc = KL_ili*(iliL_LN-L0_ili) - (KP2_ili_pq*(pq-P0_ili_pq2)) + KL_ili_ham*(hamL_LN-L0_ili_ham) - KV2_ili_pq*pqV;
        % tibialis anterior
        tibL_exc = KL_tib * (tibL_LN - L0_tib) + KF_tib_sol * solL_FN;

    case 4 % landing
        % hamstrings
        hamL_exc = KF_ham_glu * gluL_FN;
        % gluteus maximus
        gluL_exc = KF_glu * gluL_FN;
        % ilipsoas
        iliL_exc = KL_ili*(iliL_LN-L0_ili) - (KP2_ili_pq*(pq-P0_ili_pq2)) + KL_ili_ham*(hamL_LN-L0_ili_ham) - KV2_ili_pq*pqV;
        % tibialis anterior
        tibL_exc = KL_tib * (tibL_LN - L0_tib) + KF_tib_sol * solL_FN;

    otherwise
        error('invalid muscle index.');

end

muscleExcitations(1)  = hamR_exc;
muscleExcitations(2)  = gluR_exc;
muscleExcitations(3)  = iliR_exc;
muscleExcitations(4)  = vasR_exc;
muscleExcitations(5)  = gasR_exc;
muscleExcitations(6)  = solR_exc;
muscleExcitations(7)  = tibR_exc;
muscleExcitations(8)  = hamL_exc;
muscleExcitations(9)  = gluL_exc;
muscleExcitations(10) = iliL_exc;
muscleExcitations(11) = vasL_exc;
muscleExcitations(12) = gasL_exc;
muscleExcitations(13) = solL_exc;
muscleExcitations(14) = tibL_exc;

% 下面这两句限幅是必要的，但是在debug之后再取消注释
muscleExcitations(muscleExcitations > 1) = 1;
muscleExcitations(muscleExcitations < 0) = 0;

end